apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodexample
  name: nodexampleservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodexample
  type: LoadBalancer
status:
  loadBalancer: {}
