openapi: 3.0.0
info:
  title: CRUD AI App API
  version: 1.0.0
  description: A Node.js CRUD API with AI integration

servers:
  - url: http://localhost:3000

paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: Created

  /users/ai/summary:
    get:
      summary: Get AI-generated summary of users
      responses:
        '200':
          description: Summary returned
